### ISSUE TITLE
Conda config and labels

### ISSUE THREAD

**Issue by hoelzer** [rki-mf1/PanAdapt#4]
Add labels to all your processes and define a `configs/conda.config`. Add a `envs` folder where you can place conda yml files for all processes and where you define the dependencies and fix tool versions for reproducibility.

Then adjust your `nextflow.config` to load the necessary `configs/*.config`, for example when using `-profile local,conda` or `-profile slurm,conda`. 

As some example, see https://github.com/hoelzer/clean or https://github.com/rki-mf1/CoVpipe2 or other nextflow repos.

**Comment by StefanFrankBio** [comment]
I understand the [reason](https://www.nextflow.io/docs/latest/conda.html#best-practices) for creating a separate conda profile and conda environments for each process. But why are the environment files assigned in conda.config instead of directly in the conda profile block? What's the advantage of doing that?

**Comment by hoelzer** [comment]
You mean why we point to the different environment files from within the `conda.config` instead of doing that in the conda profile block in the `nextflow.config`?

My main reason is to keep the `nextflow.config` clean. 

It's also easier to maintain: all dependencies for different "engines" are defined in conda.config or docker.config, ... (We likely will add containers at some point)

Another reason might be, that you can inject configurations in nextflow. So let's say someone wants to use different conda environments for whatever reason. Than this person can inject another configuration file via `-c` and overwrite stuff. I am not sure if this works when the environments are defined in the `nextflow.config` because what is written their might have priority over injected configurations.

The last paragraph I am not 100% sure, as I said. 

Maybe @MarieLataretu has an additional take on that :)

**Comment by MarieLataretu** [comment]
Hi there,

from my experience, there are usually two use cases: a) reusable modules or b) one pipeline as a closed system.

For a) it is more handy to have the engine and executor settings directly with the process, e.g. in a nf-core module ([here ](https://github.com/nf-core/modules/blob/master/modules/nf-core/abacas/main.nf#L5) and [here](https://github.com/nf-core/modules/blob/master/modules/nf-core/abacas/environment.yml)). If you have the module directory, you can plug it in anywhere and it should work.

As Martin mentioned, for b) it's nice to have a clean `nextflow.config`. If you want to change something for all conda envs, you can directly go there instead of checking every module - or a super long config file.

Regarding the config injection: this should not be an issue, since `-c my_config` has a higher prioritization than any `nextflow.config`: https://www.nextflow.io/docs/latest/config.html#configuration-file

**Comment by hoelzer** [comment]
Ah ok, thanks for the clarification! 

Okay, so it's up to you @StefanFrankBio. I come from the b) world and like to have things separated nicely and specific files where I can change the version of an env or container for the whole pipeline. 

Also, I think PanAdapt will be more of a pipeline as a closed system than a modular framework where single processes will be used elsewhere.
